### ISSUE TITLE
No Matches - TypeError

### ISSUE THREAD

**Issue by echos-echo** [OG-FSA-2208/Optimate#21]
TypeError happens when a user has no matches
<img width="999" alt="Screen_Shot_2022-10-11_at_8 00 16_AM" src="https://user-images.githubusercontent.com/61574136/195009378-bdcbad77-1dae-4ec0-8200-7a703ed56f2f.PNG">

**Comment by zachty** [comment]
Needs to be fixed as a part of the matching algorithm when we get around to it. Matching two people should add user ID to one another's array of matches.
