### ISSUE TITLE
NavBar on user logged in

### ISSUE THREAD

**Issue by echos-echo** [OG-FSA-2208/Optimate#29]
- when refreshing page, NavBar view suggests that user is 'logged out' but clicking home redirects them to 'logged in' view
- (try logging in and refreshing the page and clicking on stuff to see what happens)
- re: above — clicking on login/signup even when a user is logged in and page is refreshed leads them to the login/signup page (should not be allowed to login when user is already logged in)
- clicking on an unavailable page (redirects to 404), NavBar shows a 'logged out' view

**Comment by zachty** [comment]
store disappears when page refreshes. Need to repopulate store with user info on 404 page.
